# Generated by Django 5.1.4 on 2025-01-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_categoria_producto_delete_category_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
