# Generated by Django 5.1.4 on 2025-01-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_producto_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='tipo_producto',
            field=models.CharField(choices=[('maquinaria', 'Maquinaria'), ('repuestos_lubricantes', 'Repuestos y Lubricantes'), ('ambos', 'Ambos')], default='maquinaria', max_length=30, verbose_name='Tipo de Producto'),
        ),
    ]
