# Generated by Django 5.1.4 on 2025-01-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_proveedor_tipo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tipo_categoria',
            field=models.CharField(blank=True, choices=[('maquinaria', 'Maquinaria'), ('repuestos_lubricantes', 'Repuestos y Lubricantes')], max_length=30, null=True, verbose_name='Tipo de Categoría'),
        ),
    ]
