# Generated by Django 5.1.4 on 2025-01-15 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_categoria_tipo_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='tipo_categoria',
        ),
    ]
