# Generated by Django 5.1.4 on 2025-01-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_categoria_tipo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proveedores/', verbose_name='Imagen del proveedor'),
        ),
    ]
