# Generated by Django 5.1.4 on 2025-01-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_imagenproducto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagenProducto',
        ),
    ]
