# Generated by Django 5.1.4 on 2025-01-21 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_imagenproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, verbose_name='Nombre de la característica')),
                ('valor', models.CharField(max_length=255, verbose_name='Valor de la característica')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='inventory.producto', verbose_name='Producto')),
            ],
        ),
    ]
