# Generated by Django 5.1.4 on 2025-01-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_caracteristica'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caracteristica',
        ),
    ]
