# Generated by Django 5.1.4 on 2025-01-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_delete_caracteristica'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='brochures/', verbose_name='Brochure PDF'),
        ),
    ]
