# Generated by Django 5.1.4 on 2025-02-21 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_producto_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='tipo_producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='inventory.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
