# Generated by Django 5.1.4 on 2025-02-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_categoria_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(blank=True, choices=[('maquinaria', 'Maquinaria'), ('repuestos_lubricantes', 'Repuestos y Lubricantes'), ('ambos', 'Ambos')], max_length=30, null=True, verbose_name='Tipo de Producto'),
        ),
    ]
