# Generated by Django 5.1.4 on 2025-02-21 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_producto_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
    ]
